language: php

php:
    - 7.0.8
    - 7.1

env:
    - SYMFONY_VERSION="^3.4"
    - SYMFONY_VERSION="^4"
    - SYMFONY_VERSION=dev-master

matrix:
    exclude:
        - php: 7.0.8
          env: SYMFONY_VERSION="^4"
        - php: 7.0.8
          env: SYMFONY_VERSION=dev-master

install:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}

before_script:
    - curl -sSf -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
    - composer install --prefer-source --dev

script: vendor/bin/simple-phpunit

notifications:
    email:
        - daniel@silverback.is

after_success:
    - bash <(curl -s https://codecov.io/bash)