language: php
php:
    - '7.0.8'
    - '7.1'
before_script:
    - curl -sSf -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
env:
    - SYMFONY_VERSION="3.4.*"
    - SYMFONY_VERSION="4.1.*"
    - SYMFONY_VERSION=dev-master
install:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}
before_script:
    - composer install --prefer-source --no-interaction --dev
script: phpunit
notifications:
    on_success: never
    on_failure: always
    email:
        - daniel@silverback.is
