<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\Container17Wiqxs\TestsEmptyDebugProjectContainer::class, false)) {
    require __DIR__.'/Container17Wiqxs/TestsEmptyDebugProjectContainer.php';
}

if (!class_exists(TestsEmptyDebugProjectContainer::class, false)) {
    class_alias(\Container17Wiqxs\TestsEmptyDebugProjectContainer::class, TestsEmptyDebugProjectContainer::class, false);
}

return new \Container17Wiqxs\TestsEmptyDebugProjectContainer();
