<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cache_warmer' shared service.

require_once $this->targetDirs[5].'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php';

return $this->services['cache_warmer'] = new \Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate(new RewindableGenerator(function () {
    yield 0 => ($this->privates['router.cache_warmer'] ?? $this->load(__DIR__.'/getRouter_CacheWarmerService.php'));
    yield 1 => ($this->privates['serializer.mapping.cache_warmer'] ?? $this->load(__DIR__.'/getSerializer_Mapping_CacheWarmerService.php'));
    yield 2 => ($this->privates['twig.cache_warmer'] ?? $this->load(__DIR__.'/getTwig_CacheWarmerService.php'));
    yield 3 => ($this->privates['twig.template_cache_warmer'] ?? $this->load(__DIR__.'/getTwig_TemplateCacheWarmerService.php'));
}, 4));
