<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cache.system' shared service.

require_once $this->targetDirs[5].'/vendor/psr/cache/src/CacheItemPoolInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/cache/Adapter/AdapterInterface.php';
require_once $this->targetDirs[5].'/vendor/psr/log/Psr/Log/LoggerAwareInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/cache/ResettableInterface.php';
require_once $this->targetDirs[5].'/vendor/psr/log/Psr/Log/LoggerAwareTrait.php';
require_once $this->targetDirs[5].'/vendor/symfony/cache/Traits/AbstractTrait.php';
require_once $this->targetDirs[5].'/vendor/symfony/cache/Adapter/AbstractAdapter.php';

return $this->services['cache.system'] = \Symfony\Component\Cache\Adapter\AbstractAdapter::createSystemCache('FtiZ7eaE8g', 0, 'G5xUDgijg7awwhKWnBmCpw', ($this->targetDirs[0].'/pools'), ($this->privates['logger'] ?? $this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger()));
