<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'serializer' shared service.

require_once $this->targetDirs[5].'/vendor/symfony/serializer/SerializerInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Normalizer/NormalizerInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Normalizer/ContextAwareNormalizerInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Normalizer/DenormalizerInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Normalizer/ContextAwareDenormalizerInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Encoder/EncoderInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Encoder/ContextAwareEncoderInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Encoder/DecoderInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Encoder/ContextAwareDecoderInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Serializer.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/SerializerAwareInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Normalizer/ObjectToPopulateTrait.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/SerializerAwareTrait.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Normalizer/JsonSerializableNormalizer.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Normalizer/DateTimeNormalizer.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Normalizer/DateIntervalNormalizer.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Normalizer/DataUriNormalizer.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Normalizer/ArrayDenormalizer.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Encoder/NormalizationAwareInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Encoder/XmlEncoder.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Encoder/JsonEncoder.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Encoder/YamlEncoder.php';
require_once $this->targetDirs[5].'/vendor/symfony/serializer/Encoder/CsvEncoder.php';

return $this->services['serializer'] = new \Symfony\Component\Serializer\Serializer(array(0 => new \Symfony\Component\Serializer\Normalizer\JsonSerializableNormalizer(), 1 => new \Symfony\Component\Serializer\Normalizer\DateTimeNormalizer(), 2 => new \Symfony\Component\Serializer\Normalizer\DateIntervalNormalizer(), 3 => new \Symfony\Component\Serializer\Normalizer\DataUriNormalizer(), 4 => new \Symfony\Component\Serializer\Normalizer\ArrayDenormalizer()), array(0 => new \Symfony\Component\Serializer\Encoder\XmlEncoder(), 1 => new \Symfony\Component\Serializer\Encoder\JsonEncoder(), 2 => new \Symfony\Component\Serializer\Encoder\YamlEncoder(), 3 => new \Symfony\Component\Serializer\Encoder\CsvEncoder()));
