<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'serializer.mapping.cache_warmer' shared service.

require_once $this->targetDirs[5].'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
require_once $this->targetDirs[5].'/vendor/symfony/framework-bundle/CacheWarmer/AbstractPhpFileCacheWarmer.php';
require_once $this->targetDirs[5].'/vendor/symfony/framework-bundle/CacheWarmer/SerializerCacheWarmer.php';

return $this->privates['serializer.mapping.cache_warmer'] = new \Symfony\Bundle\FrameworkBundle\CacheWarmer\SerializerCacheWarmer(array(), ($this->targetDirs[0].'/serialization.php'), ($this->privates['cache.serializer'] ?? $this->load(__DIR__.'/getCache_SerializerService.php')));
