<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'twig' shared service.

require_once $this->targetDirs[5].'/vendor/twig/twig/lib/Twig/Environment.php';
require_once $this->targetDirs[5].'/vendor/twig/twig/lib/Twig/LoaderInterface.php';
require_once $this->targetDirs[5].'/vendor/twig/twig/lib/Twig/ExistsLoaderInterface.php';
require_once $this->targetDirs[5].'/vendor/twig/twig/lib/Twig/SourceContextLoaderInterface.php';
require_once $this->targetDirs[5].'/vendor/twig/twig/lib/Twig/Loader/Filesystem.php';
require_once $this->targetDirs[5].'/vendor/twig/twig/lib/Twig/Profiler/Profile.php';
require_once $this->targetDirs[5].'/vendor/twig/twig/lib/Twig/ExtensionInterface.php';
require_once $this->targetDirs[5].'/vendor/twig/twig/lib/Twig/Extension.php';
require_once $this->targetDirs[5].'/vendor/twig/twig/lib/Twig/Extension/Profiler.php';
require_once $this->targetDirs[5].'/vendor/symfony/twig-bridge/Extension/ProfilerExtension.php';
require_once $this->targetDirs[5].'/vendor/symfony/twig-bridge/Extension/TranslationExtension.php';
require_once $this->targetDirs[5].'/vendor/symfony/twig-bridge/Extension/CodeExtension.php';
require_once $this->targetDirs[5].'/vendor/symfony/twig-bridge/Extension/RoutingExtension.php';
require_once $this->targetDirs[5].'/vendor/symfony/twig-bridge/Extension/YamlExtension.php';
require_once $this->targetDirs[5].'/vendor/symfony/twig-bridge/Extension/HttpKernelExtension.php';
require_once $this->targetDirs[5].'/vendor/symfony/twig-bridge/Extension/HttpFoundationExtension.php';
require_once $this->targetDirs[5].'/vendor/twig/twig/lib/Twig/Extension/Debug.php';
require_once $this->targetDirs[5].'/vendor/symfony/twig-bridge/AppVariable.php';
require_once $this->targetDirs[5].'/vendor/twig/twig/lib/Twig/RuntimeLoaderInterface.php';
require_once $this->targetDirs[5].'/vendor/twig/twig/lib/Twig/ContainerRuntimeLoader.php';
require_once $this->targetDirs[5].'/vendor/symfony/twig-bundle/DependencyInjection/Configurator/EnvironmentConfigurator.php';

$a = ($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack());

$b = new \Twig\Loader\FilesystemLoader(array(), $this->targetDirs[3]);
$b->addPath(($this->targetDirs[3].'/Resources/views'), 'JsSdkBundleTest');
$b->addPath(($this->targetDirs[5].'/vendor/symfony/framework-bundle/Resources/views'), 'Framework');
$b->addPath(($this->targetDirs[5].'/vendor/symfony/framework-bundle/Resources/views'), '!Framework');
$b->addPath(($this->targetDirs[5].'/vendor/symfony/twig-bundle/Resources/views'), 'Twig');
$b->addPath(($this->targetDirs[5].'/vendor/symfony/twig-bundle/Resources/views'), '!Twig');
$b->addPath(($this->targetDirs[5].'/Resources/views'), 'JsSdk');
$b->addPath(($this->targetDirs[5].'/Resources/views'), '!JsSdk');

$c = new \Symfony\Bridge\Twig\AppVariable();
$c->setEnvironment('empty');
$c->setDebug(true);
if ($this->has('request_stack')) {
    $c->setRequestStack($a);
}

$this->services['twig'] = $instance = new \Twig\Environment($b, array('paths' => array(($this->targetDirs[3].'/Resources/views') => 'JsSdkBundleTest'), 'exception_controller' => 'twig.controller.exception:showAction', 'form_themes' => $this->parameters['twig.form.resources'], 'autoescape' => 'name', 'cache' => ($this->targetDirs[0].'/twig'), 'charset' => 'UTF-8', 'debug' => true, 'default_path' => ($this->targetDirs[3].'/templates'), 'date' => array('format' => 'F j, Y H:i', 'interval_format' => '%d days', 'timezone' => NULL), 'number_format' => array('decimals' => 0, 'decimal_point' => '.', 'thousands_separator' => ',')));

$instance->addExtension(new \Symfony\Bridge\Twig\Extension\ProfilerExtension(new \Twig\Profiler\Profile(), NULL));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\TranslationExtension(NULL));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\CodeExtension(($this->privates['debug.file_link_formatter'] ?? $this->privates['debug.file_link_formatter'] = new \Symfony\Component\HttpKernel\Debug\FileLinkFormatter(NULL)), $this->targetDirs[4], 'UTF-8'));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\RoutingExtension(($this->services['router'] ?? $this->getRouterService())));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\YamlExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\HttpKernelExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\HttpFoundationExtension($a, ($this->privates['router.request_context'] ?? $this->getRouter_RequestContextService())));
$instance->addExtension(new \Twig\Extension\DebugExtension());
$instance->addGlobal('app', $c);
$instance->addRuntimeLoader(new \Twig\RuntimeLoader\ContainerRuntimeLoader(new \Symfony\Component\DependencyInjection\ServiceLocator(array('Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime' => function () {
    return ($this->privates['twig.runtime.httpkernel'] ?? $this->load(__DIR__.'/getTwig_Runtime_HttpkernelService.php'));
}))));
(new \Symfony\Bundle\TwigBundle\DependencyInjection\Configurator\EnvironmentConfigurator('F j, Y H:i', '%d days', NULL, 0, '.', ','))->configure($instance);

return $instance;
